### ISSUE TITLE
tag cloud

### ISSUE THREAD

**Issue by baopham** [5v3n/karakuri#3]
Is it possible to have a function to get all the tags and its frequency?

**Comment by 5v3n** [comment]
Since the pages are generated in a static manner: sure.

Would love to see that feature implemented. If you have any questions while implementing the feature, feel free to drop me a line.

Looking forward to your pull request

Sven

**Comment by baopham** [comment]
For a newbie like me, it will take a while, but I will try :D this is exciting! 

Thank you

**Comment by 5v3n** [comment]
change some details of your implementation & merged it into karakuri. congrats! ;-)

**Comment by baopham** [comment]
thank you :)
